[general]
id = "cb7goxxm"
user = "user"
container_name = "silo-cb7goxxm"

[features]
workspace = true
state = true
podman = false

[podman]
args = [
  "--cap-drop=ALL",
  "--cap-add=NET_BIND_SERVICE",
  "--security-opt no-new-privileges",
  "--volume /Users/markus/etc/silo:/workspace/cb7goxxm/silo:Z",
  "--workdir /workspace/cb7goxxm/silo",
  "--volume silo-state:/state/global:Z",
]
extra_args = []
command = "fish --login"
