[general]
id = "xqmrs9xj"
user = "markus"

[features]
shared_volume = true
podman = false

[shared_volume]
name = "silo-shared"
paths = ["$HOME/.local/share/fish/fish_history", "$HOME/.claude.json", "$HOME/.claude/"]

[connect]
command = "fish --login"

[podman.create]
arguments = ["--cap-drop=ALL", "--cap-add=NET_BIND_SERVICE", "--security-opt", "no-new-privileges"]
