[general]
user = "markus"

[persistence]
shared_paths = [
  "$HOME/.local/share/fish/fish_history",
  "$HOME/.claude.json",
  "$HOME/.claude/",
  "$HOME/.cache/opencode/",
  "$HOME/.local/share/opencode/",
  "$HOME/.local/state/opencode/"
]

[podman]
create_args = []