[general]
user = "markus"

[persistence]
private_paths = [
  "$HOME/.local/share/fish/fish_history",
]
shared_paths = [
  "$HOME/.claude.json",
  "$HOME/.claude/",
  "$HOME/.cache/opencode/",
  "$HOME/.local/share/opencode/",
  "$HOME/.local/state/opencode/"
]

[podman]
create_args = []
