[connect]
command = "fish --login"

[features]
shared_volume = true
podman = false

[shared_volume]
name  = "silo-shared"
paths = [
  "$HOME/.local/share/fish/fish_history",
  "$HOME/.claude.json",
  "$HOME/.claude/"
]

[podman.create]
arguments = []
