FROM fedora:latest

# See: https://github.com/containers/image_build/blob/main/podman/Containerfile

RUN dnf -y makecache && \
    dnf -y update && \
    rpm --setcaps shadow-utils 2>/dev/null && \
    dnf -y install \
      bash \
      ca-certificates \
      coreutils \
      curl \
      shadow-utils \
      sudo \
      util-linux \
      xz && \
    dnf clean all && \
    rm -fv /etc/machine-id /var/lib/systemd/random-seed /var/lib/dnf/repos/*/countme && \
    rm -fv /usr/lib/systemd/profile.d/* && \
    rm -rf /var/cache /var/log/dnf* /var/log/hawkey.log /var/log/yum.*

# User setup

RUN groupadd --gid 1000 {{.User}} && \
  useradd --uid 1000 --gid 1000 -m -s /bin/bash {{.User}} && \
  usermod -aG wheel {{.User}} && \
  echo '%wheel ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/wheel && \
  chmod 0440 /etc/sudoers.d/wheel

# Enable rootless containers

RUN echo -e "root:1:65535\n{{.User}}:1:999\n{{.User}}:1001:64535" > /etc/subuid && \
    echo -e "root:1:65535\n{{.User}}:1:999\n{{.User}}:1001:64535" > /etc/subgid

ENV _CONTAINERS_USERNS_CONFIGURED=""

# Nix build users (see: https://hub.docker.com/r/nixos/nix/dockerfile/)

RUN mkdir -p /var/empty && \
  groupadd --gid 30000 nixbld && \
  for i in $(seq 1 30); do \
    useradd \
      --uid $((30000 + i)) \
      --gid nixbld \
      --home-dir /var/empty \
      --no-create-home \
      --shell /usr/sbin/nologin \
      --comment "Nix build user $i" \
      nixbld$i ; \
  done

# Shared volume directory

RUN mkdir -p {{.SharedVolumeMount}} && \
  chown {{.User}}:{{.User}} /silo {{.SharedVolumeMount}}

# Nix configuration

RUN mkdir -p /etc/nix && \
  echo 'sandbox = false' > /etc/nix/nix.conf && \
  echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf && \
  echo 'auto-optimise-store = true' >> /etc/nix/nix.conf

# Entrypoint

CMD ["sleep", "infinity"]

# Install Nix

USER {{.User}}
WORKDIR {{.Home}}
ENV USER={{.User}}

RUN curl -L https://nixos.org/nix/install | sh -s -- --no-daemon
ENV PATH={{.Home}}/.nix-profile/bin:{{.Home}}/.nix-profile/sbin:$PATH

# Install home-manager

RUN nix profile add nixpkgs#home-manager && \
    nix-store --gc

ADD --chown={{.User}}:{{.User}} flake.nix {{.Home}}/.config/home-manager/flake.nix
ADD --chown={{.User}}:{{.User}} home-user.nix {{.Home}}/.config/home-manager/home-user.nix
ADD --chown={{.User}}:{{.User}} home-workspace-empty.nix {{.Home}}/.config/home-manager/home-workspace.nix

RUN home-manager switch --flake $HOME/.config/home-manager && \
    nix-store --gc
